apiVersion: v1
kind: Pod
metadata:
  name: irsa-test
  namespace: spark-jobs
spec:
  serviceAccountName: spark-job-sa
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["/bin/sh", "-c", "sleep 3600"]
  restartPolicy: Never
