---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lambda-spark-trigger
  namespace: spark-jobs
---
apiVersion: v1
kind: Secret
metadata:
  name: lambda-spark-trigger-token
  namespace: spark-jobs
  annotations:
    kubernetes.io/service-account.name: lambda-spark-trigger
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lambda-spark-manager
rules:
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lambda-spark-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lambda-spark-manager
subjects:
- kind: ServiceAccount
  name: lambda-spark-trigger
  namespace: spark-jobs
